[package]
name = "qrkod"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-files = "0.6"
qrcode = "0.14.1"
image = { version = "0.25.0", features = ["png"] }
serde = { version = "1.0", features = ["derive"] }